### ISSUE TITLE
Please tell me when to share this project and look forward to your sharing

### ISSUE THREAD

**Issue by maxiaoliang1989120** [Lydorn/Polygonization-by-Frame-Field-Learning#1]
Please tell me when to share this project and look forward to your sharing

**Comment by Lydorn** [comment]
> Please tell me when to share this project and look forward to your sharing
Thank you for your interest, I will likely upload the code next week, once I've finished cleaning it up.
For now you can read our pre-print: https://arxiv.org/abs/2004.14875
