### ISSUE TITLE
share weights

### ISSUE THREAD

**Issue by SerinaWei** [Lydorn/Polygonization-by-Frame-Field-Learning#3]
Thanks for the excellent work! I would like to check how modules such as polygonise_asm.py work, but doesn't have the weights/checkpoints to do that.

**Comment by Lydorn** [comment]
@SerinaWei Sorry for the delay, I've added a link to download a few trained models in the main README along with some instructions to place them correctly in the project structure. I hope you'll be able to check out polygonise_asm.py  now!

**Comment by SerinaWei** [comment]
Thank you so much! @Lydorn
