### ISSUE TITLE
problem while using docker run

### ISSUE THREAD

**Issue by sarath0993** [Lydorn/Polygonization-by-Frame-Field-Learning#5]
As instructed I created docker image, but when i run the image using the following command shows error

`docker run --rm -it --init --gpus 1 --ipc=host --network=host-e -v "./data:/data" lydorn/frame-field-learning`

**Unable to find image 'frame-field-learning:latest' locally**

But when I run `docker ps -a` it shows the image

**Comment by Lydorn** [comment]
I think the problem is because you should use "lydorn/frame-field-learning:1.4" as the image name.

**Comment by sarath0993** [comment]
Got it. This solved the issue. There is nothing found inside the container, should I copy codes inside container? I copied codes and pretrained models but it got erased after I exit from the container. Please guide me

**Comment by sarath0993** [comment]
Finally I made it work! Thanks!!

**Comment by yeshwanth95** [comment]
> Finally I made it work! Thanks!!

Hi Sarath. You mind elaborating how you managed to get it to work? I too am not finding anything in the /app directory of the docker image.
