### ISSUE TITLE
Error in inference

### ISSUE THREAD

**Issue by sarath0993** [Lydorn/Polygonization-by-Frame-Field-Learning#6]
While running inference, it shows error for the below mentioned two trained models, but it works well for inria model. Please help me to resolve this

mapping_dataset.unet_resnet101_pretrained.train_val
mapping_dataset.unet_resnet101_pretrained.field_off.train_val

```
Traceback (most recent call last):
  File "main.py", line 374, in <module>
    main()
  File "main.py", line 364, in main
    launch_inference_from_filepath(args)
  File "main.py", line 175, in launch_inference_from_filepath
    inference_from_filepath(config, args.in_filepath, backbone)
  File "/app/Polygonization-by-Frame-Field-Learning/frame_field_learning/inference_from_filepath.py", line 45, in inference_from_filepath
    tile_data = inference.inference(config, model, sample, compute_polygonization=True)
  File "/app/Polygonization-by-Frame-Field-Learning/frame_field_learning/inference.py", line 28, in inference
    inference_no_patching(config, model, tile_data)
  File "/app/Polygonization-by-Frame-Field-Learning/frame_field_learning/inference.py", line 51, in inference_no_patching
    pred, batch = network_inference(config, model, batch)
  File "/app/Polygonization-by-Frame-Field-Learning/frame_field_learning/inference.py", line 17, in network_inference
    pred, batch = model(batch, tta=config["eval_params"]["test_time_augmentation"])
KeyError: 'test_time_augmentation'
```

**Comment by Lydorn** [comment]
Ah yes, to bypass this issue, add the following argument to main.py:
--config configs/config.mapping_dataset.unet_resnet101_pretrained.train_val.json
to add this missing 'test_time_augmentation' parameter.

**Comment by Lydorn** [comment]
Or better yet, I've just updated the runs in the shared Google Drive to include more recent ones that work as intended, solving the issue directly:
[https://drive.google.com/drive/folders/1poTQbpCz12ra22CsucF_hd_8dSQ1T3eT?usp=sharing](https://drive.google.com/drive/folders/1poTQbpCz12ra22CsucF_hd_8dSQ1T3eT?usp=sharing)
You can delete the runs you have for mapping_dataset.unet_resnet101_pretrained.train_val and mapping_dataset.unet_resnet101_pretrained.field_off.train_val and download the new ones from the link.

**Comment by sarath0993** [comment]
Thanks! This trained model `mapping_dataset.unet_resnet101_pretrained.field_off.train_val`  works perfectly now, But when using this model `mapping_dataset.unet_resnet101_pretrained.train_val`  it is showing an error message, Any quickfix for this issue?

**Comment by Lydorn** [comment]
What is the error message for mapping_dataset.unet_resnet101_pretrained.train_val ?

**Comment by sarath0993** [comment]
@Lydorn Sorry for the very late response, I am getting this error 

`Traceback (most recent call last):
  File "main.py", line 374, in <module>
    main()
  File "main.py", line 364, in main
    launch_inference_from_filepath(args)
  File "main.py", line 175, in launch_inference_from_filepath
    inference_from_filepath(config, args.in_filepath, backbone)
  File "/app/Polygonization-by-Frame-Field-Learning/frame_field_learning/inference_from_filepath.py", line 26, in inference_from_filepath
    model = inference.load_checkpoint(model, checkpoints_dirpath, config["device"])
  File "/app/Polygonization-by-Frame-Field-Learning/frame_field_learning/inference.py", line 162, in load_checkpoint
    model.load_state_dict(checkpoint['model_state_dict'])
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for FrameFieldModel:
	size mismatch for seg_module.3.weight: copying a param with shape torch.Size([2, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 32, 1, 1]).
	size mismatch for seg_module.3.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for crossfield_module.0.weight: copying a param with shape torch.Size([32, 34, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 33, 3, 3]).
`

**Comment by Lydorn** [comment]
Thanks for bringing this to my attention. I looked and it is was due to an error in the config.json file inside the run folder of 'mapping_dataset.unet_resnet101_pretrained.train_val'. I fixed it but you have to download this config.json from Google Drive again.

**Comment by sarath0993** [comment]
Thanks! I will run it again and let you know

**Comment by sarath0993** [comment]
@Lydorn The trained model `mapping_dataset.unet_resnet101_pretrained.train_val` works great! Thanks again
