### ISSUE TITLE
Training flowline

### ISSUE THREAD

**Issue by sarath0993** [Lydorn/Polygonization-by-Frame-Field-Learning#8]
Could you please tell me the training procedure for Indria dataset from scratch? I have aerial images and corresponding masks in .png format right now.

**Comment by Lydorn** [comment]
So for the Inria dataset there are 2 possibilities:
- Download OSM annotations for the images. In my case I also fixed the alignment of those annotations with a previous method of mine. To use this version of the dataset, reference the `dataset_params.inria_dataset_osm_aligned.json` config file.
- Convert the available ground truth masks with the frame field polygonization method. To use this version of the dataset, reference the `dataset_params.inria_dataset_polygonized.json` config file.

I added details for this in the main README as well as a link to download all those different ground truth files so you can get started right away!
